spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pro_spring?useSSL=true&useUnicode=true&characterEncoding=utf8
    username: spring
    password: qZF08fDcidSRJ2CI
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
    host: localhost
    port: 6379
    password: KSNwJwcOUj2KBLJQ

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB


file:
  upload:
    location:

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.codve.mybatis.model.data.object
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

