spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pro_spring?charset=utf-8&useSSL=true
    username: spring
    password: qZF08fDcidSRJ2CI

  redis:
    database: 0
    host: localhost
    port: 6379
    password: KSNwJwcOUj2KBLJQ


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.codve.mybatis.model
