spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pro_spring?charset=utf-8&useSSL=true
    username: spring
    password: qZF08fDcidSRJ2CI


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliases-package: com.codve.mybatis.model
