spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pro_spring?characterEncoding=utf-8&useSSL=true
    username: spring
    password: qZF08fDcidSRJ2CI
    druid:
      initial-size: 4
      max-active: 8
      min-idle: 1
      max-wait: 30000
      validation-query: select 1
      validation-query-timeout: 30000
